apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: jvilo/ping-pong:2.7
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pingpong-db-config
            - secretRef:
                name: pingpong-db-secret

