apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-and-pingpong-ing
  namespace: exercises
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
    # This enables optional backend config if needed later
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-service
            port:
              number: 80
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: ping-pong-service
            port:
              number: 80

