apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
  namespace: exercises
spec:
  selector:
    app: ping-pong
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
