apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: todo-backend-healthcheck
  namespace: project
spec:
  healthCheck:
    checkIntervalSec: 10
    port: 80
    type: HTTP
    requestPath: /api/todos
    timeoutSec: 5