apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: writer
          image: jvilo/log-output-writer:1.0
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
        - name: reader
          image: jvilo/log-output-reader:1.11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
