apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-reader
          image: jvilo/log-output-reader:2.2
          ports:
            - containerPort: 8080
          env:
            - name: PING_PONG_URL
              value: "http://ping-pong-service/pings"
        - name: log-output-writer
          image: jvilo/log-output-writer:2.1
