apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - todo-db-config.yaml
  - todo-db-secret.yaml
  - postgres.yaml
  - todo-cronjob.yaml
  - ../todo-backend/manifests  # Include backend as a submodule
