apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo-generator
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: todo-generator
              image: curlimages/curl:8.5.0
              command:
                - /bin/sh
                - -c
                - |
                  URL=$(curl -s -I https://en.wikipedia.org/wiki/Special:Random | grep -i location | awk '{print $2}' | tr -d '\r')
                  echo "Generated random article: $URL"
                  curl -X POST -H "Content-Type: application/json" \
                       -d "{\"todo\":\"Read $URL\"}" \
                       http://todo-backend-service/api/todos
