name: Delete Environment on Branch Deletion

on:
  delete:
    branches:
      - '**'  # Trigger on deletion of any branch

jobs:
  delete-namespace:
    name: Delete GKE Namespace
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials dwk-cluster \
            --zone europe-north1-c \
            --project ${{ secrets.GKE_PROJECT }}

      - name: Delete GKE namespace
        run: |
          # Get branch name from deleted ref
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          # Don't delete main branch namespace
          if [ "$BRANCH_NAME" != "main" ]; then
            echo "Deleting namespace $BRANCH_NAME"
            kubectl delete namespace $BRANCH_NAME || true
          else
            echo "Skipping deletion of main namespace"
          fi
