name: Release application

on:
  push:
    branches:
      - '**'   # Run for all branches

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-c
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: todo-repository
  IMAGE: todo-app
  SERVICE: todo-backend
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: project   # 👈 this tells GitHub to use Environment Secrets from "project"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}   # 👈 comes from Environment secrets now

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker to use gcloud
        run: gcloud --quiet auth configure-docker $REGISTRY

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Form image tag
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: ./todo_app
        run: docker build -t $IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy to GKE (per-branch environment)
        run: |
          # Use branch name as namespace, except for main
          if [ "${{ env.BRANCH }}" = "main" ]; then
            NAMESPACE="project"
          else
            NAMESPACE="${{ env.BRANCH }}"
          fi

          echo "Using namespace: $NAMESPACE"

          # Ensure namespace exists
          kubectl create namespace $NAMESPACE || true

          # Switch context to that namespace
          kubectl config set-context --current --namespace=$NAMESPACE

          # Move into manifests folder
          cd todo_app/manifests

          # Update kustomization for this namespace and image
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image $REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE=$IMAGE_TAG

          # Apply and verify rollout
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$SERVICE -n $NAMESPACE
          kubectl get services -n $NAMESPACE -o wide

