name: Release application

on:
  push:
    branches:
      - '**'   # run for all branches (main + feature branches)

env:
  PROJECT_ID: dwk-gke-2025-476414        # your actual GCP project ID (plain text)
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-c
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: todo-repository
  IMAGE: todo-app
  SERVICE: todo-backend
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: dwk-gke-2025-476414

      - name: Configure Docker to use gcloud
        run: gcloud --quiet auth configure-docker $REGISTRY

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Form image tag
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: ./todo_app
        run: docker build -t $IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy to GKE (per-branch environment)
        run: |
          if [ "${{ env.BRANCH }}" = "main" ]; then
            NAMESPACE="project"
          else
            NAMESPACE="${{ env.BRANCH }}"
          fi

          echo "Using namespace: $NAMESPACE"

          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE

          cd todo_app/manifests
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image $REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE=$IMAGE_TAG

          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$SERVICE -n $NAMESPACE


